name: Terraform CI/CD

on: 
  push: 
    branches: 
      - main
  pull_request: 
    branches: 
      - main

jobs: 
  terraform: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Configure AWS Credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      run: |
        mkdir -p ~/.aws
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
        echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
        echo "region = $AWS_REGION" >> ~/.aws/config

    - name: Terraform Format Check
      run: terraform fmt -check

    - name: Terraform Init
      run: cd gitterraform/ && terraform init

    # - name: Terraform Plan
    #   run: cd gitterraform/ && terraform plan

    # - name: Terraform Apply
    #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    #   run: cd gitterraform/ && terraform apply -auto-approve 
    #   env:
    #     TFE_TOKEN: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Destroy
      run: |
        cd gitterraform/
        terraform init
        terraform plan -destroy
        terraform destroy

    

